# My Emacs Configuration

This repository documents my jounery back to becoming a regular Emacs user.

* Setup

** Clone the repository to `$HOME/.emacs.d/`

** Change directory to project root

** Initialize `custom.el`: `$ touch custom.el`

* Edit

** Search
Several tools need to be installed to allow fast project traversal and string search.

** Ag

*** Install

**** On Linux: `$ sudo apt install silversearcher-ag`

****  On Mac: `$ brew install the_silver_searcher`

* Configurations
  * Set up the `.agignore` file, or a global `$HOME/.agignore` file
  * Install `ag` melpa


** Language/Framework Server Protocols

*** Angular
Run
#+begin_src bash
$ sudo npm install -g @angular/language-service@next typescript @angular/language-server`
#+end_src

***  Go
Make sure `gopls` is installed and `$GOPATH/bin` is in emacs' executable paths.


***  PHP (language server not aways working)

If running into issue `LSP :: example_file_name no in project or it is blacklisted`, add project root
to LSP workspace or remove it from the blacklist:
`M-x lsp-workspace-blacklist-remove` or `M-s lsp-workspace-folders-add`.


***  Python3
After `elpy` is added to emacs, also install addtional system requirements:
`$ sudo apt install python3-jedi black python3-autopep8 yapf3 python3-yapf`

Then restart Emacs.


***  TypeScript

Install TypeScript language server:
#+BEGIN_SRC bash
$ npm i -g typescript-language-server
$ npm i -g typescript
#+END_SRC


Then in Emacs, install LSP server:
#+begin_src
M-x lsp-install-server RET jsts-ls RET
#+end_src
